remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Senior Research]
description: [Data structures and tests to show the value and methods of leveraging branch prediction in processors in randomized data]